In [1]:
from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer
from transformers import GenerationConfig
import pandas as pd
import re
from langchain_experimental.text_splitter import SemanticChunker
from langchain_openai.embeddings import OpenAIEmbeddings
from chunking_evaluation.chunking import KamradtModifiedChunker
from sentence_transformers import SentenceTransformer
from chunking_evaluation.chunking import ClusterSemanticChunker
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import torch
print(torch.version.cuda)

c:\Users\User\anaconda3\envs\summarization\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

12.1

In [2]:
train = pd.read_csv('data/train.csv')

In [3]:
validation = train.iloc[700:]
train = train[:700]

In [4]:
train.head()

,paper_id,text,summary
0,0,## FROM SOVEREIGNTY TO EXTRATERRITORIAL CONSCI...,"In this article, Victor Fan argues that analys..."
1,1,## 1. Introduction\n\n\nAn Electronic Health R...,Problem definition: Physicians spend more than...
2,2,## Introduction\n\n\nTranslation plays an i...,Literary translation is one of the most challe...
3,3,## 1 Problem Setup\n\n\nRecent political scien...,There is a long-running debate on evaluating f...
4,4,## INTRODUCTION\n\n\nThis article investigat...,"Recently, ‘bimajyo’ (美魔女) came into focus in J..."

In [5]:
validation.shape

(300, 3)

In [5]:
model_name = 'google/flan-t5-large'
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

Loading weights: 100%|██████████| 558/558 [00:00<00:00, 937.58it/s, Materializing param=shared.weight]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

In [7]:
indices = [10]

for i in indices:
    text = train['text'][i]
    summary = train['summary'][i]

    prompt = f"""
Summarize the following text using around 200 words at least {text}

Summary:
"""
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    input = tokenizer(prompt, return_tensors='pt')
    output = tokenizer.decode(
        model.generate(input['input_ids'], max_new_tokens=50,)[0]
    )

    print(summary)
    print("--------------------")
    print(output)

Token indices sequence length is longer than the specified maximum sequence length for this model (5852 > 512). Running this sequence through the model will result in indexing errors

OBJECTIVES: Evidence on how individual characteristics and distancing policies during the first wave of COVID-19 together influenced health behaviours is scarce. The objective of this study is to fill in this gap by studying how the propensity to engage in protective behaviours in Europe was shaped by the interplay of individual characteristics and national policies.
DESIGN: Data on individual behaviour in 27 countries came from the “Corona Survey” module of the Survey of Health, Ageing and Retirement in Europe, collected in summer 2020. As outcomes, we considered avoidant behaviours (never leaving home, reducing frequency of walks, reducing frequency of social meetings) and preventive behaviour (wearing a face mask). Among relevant policies we considered stay-at-home restrictions, mask wearing policies, and gatherings’ restrictions. Individual characteristics comprised gender, health risk of COVID-19 (older age and poor health), and activity (employment and providing help to other households).
PARTICIPANTS: Nationally representative samples of older adults (50 years and over); N=51,540 respondents (58% of women).
RESULTS: Active people (employed and helping other households) were more likely to wear face masks, but less likely to use avoidant behaviours. People at health risk (older people and those in poor health) were more likely to use all types of protective behaviours. Protective behaviours were also more frequent among women than among men. Longer duration of distancing polices correlated with more frequent protective behaviours. Distancing policies reduced social differences in the rate of protective behaviours only in case of social meetings and mask wearing.
CONCLUSIONS: Protective behaviours responded to distancing policies, but our results suggest that people used them voluntarily, especially if they were at health risk.
--------------------
<pad> The interplay of individual characteristics and national policies shaped the prevalence of COVID-19 protective behaviours among older adults in 27 European countries during spring 2020.</s>

In [8]:
indices = [10, 45, 38]
index = enumerate(indices)

In [9]:
text = train['text'][3]
paragraphs = re.split("\n\n", text)

In [10]:
split = text.split()
[' '.join(split[i:i+500]) for i in range(0, len(split), 500)]

["## 1 Problem Setup Recent political science scholarship has questioned the ability to evaluate presidential election forecasts [1]. On its face, this argument is plausible: presidential elections are rare, and state-level outcomes within presidential elections are highly correlated. If we believe we need 10 or 20 or 100 presidential elections to evaluate whether a forecast provides useful information, we could be waiting a long time wondering if we are being lead astray by forecasts or not. Despite the seeming plausibility of the argument by Grimmer, Knox, and Westwood (henceforth GKW), I argue 1 that there are several ways we may evaluate election forecasts on shorter timescales than 'decades to millennia.' As a heuristic, I argue that we can generally determine whether a forecast is better than random guessing using only publicly available data no more granular than the congressional district level on timescales of two-to-three election cycles (4-6 years in the U.S. counting both midterms and presidentials). The basic intuition underlying my argument is that there are many ways to be wrong but few ways to be right. Forecasters that make assumptions which are robust across several election cycles likely have parametric models of the world in their heads which are better than random guessing and therefore provide information. By a process of selection, forecasts that are implausibly wrong die off or are modified, leading to a marketplace of major forecasts that are generally informative. I note that in GKW's article, they conflate the general usefulness of forecasts, comparing good forecasts to one another, and potential secondary harms of probabilistic forecasts such as depressing turnout. I will focus only on determining whether forecasts provide information, not how to pick the best forecast or secondary effects of forecasts. I also note that GKW takes the strong position that presidential elections are completely different from other elections, a point I strongly disagree with. Quoting from the conclusion of GKW: Even under the most optimistic assumptions, we are far from being able to rigorously assess probabilistic forecasters' claims of superiority to conventional punditry. Yet despite the lack of demonstrable benefits, forecasts induce known harms: producing vacuous, unverifiable horse-race coverage; potentially depressing votes for forecasted winners; and misleading the public and campaigns alike. Taken together, it is hard to justify the place of forecasts in the political discourse around elections without fundamentally recalibrating claims to match the available empirical evidence. From this, it is clear that the key argument in GKW is that forecasts provide little information relative to alternatives. Determining this fully is difficult, since it requires the information in a replacement-level pundit's subjective election forecast. I will focus on demonstrating that contemporary major election forecasts can be distinguished from random guessing. My argument is that if election forecasts are clearly better than random guessing, they provide a key source of evidence about the state of politics that is different from punditry in that it is explicit about its assumptions and it has a process independent from events of incorporating new information. Forecasts",
 "help us resist being overwhelmed by hot and cold feelings in election cycles and therefore, to at least some people, provide value. They also can be presented in partisan spaces and help us combat contemporary epistemic closure in a way that hot takes (punditry) cannot. I do not engage with GKW's argument that forecasts have secondary harms such as depressing turnout. This may be true, and if it is true it should be a key consideration for how, when, and where we present election forecasts in the media. But that question is completely distinct from the key argument GKW make that forecasts provide essentially no information relative to vibes. ## 2 Paper plan First, I will use only the topline result from the 2012, 2016, and 2020 presidential elections and the forecasted probability by two major forecasters to show we can distinguish good and bad forecasts using only these minimal data points. Contrary to the argument in GKW, using only six numbers (one probability from two different forecasters over three elections) and Bayes' theorem, we can convince ourselves that one of two election forecasters is much more likely to be right. I note that GKW did not consider this simple approach. Second, I conduct a simulation which demonstrates that we can distinguish even moderately good (65-70% accuracy) forecasters from random guessing in 7 to 10 election cycles. This assumes that we look at only a single number per forecaster per election: the topline win probability. Then, I argue that we can increase the number of 'effective elections' in two different ways: we can relax the extremely strong GKW assumption that presidential elections and other elections are unrelated, and we can consider state-level outcomes (or for midterms, congressional-district level ones). I estimate that each presidential election when forecasted at the state level provides roughly 5 'elections' worth of information. ## 3 'Just Use Bayes' Theorem' The position taken by GKW is that single elections give little information. This is wrong. Let's use Bayes' theorem to show this using only six data points: the topline win probabilities from two prominent forecast models from the 2012, 2016, and 2020 presidential cycles. While this strategy will not give us classical statistical significance, it will give us a probability that each forecast is correct (given some assumptions). We will see that one forecast is much more likely to be correct than the other. The quantity we're interested in is p (forecast correct election outcome), | which we will abbreviate p f e ( | ). Using Bayes' theorem, we can turn this in to a tractable problem. <!-- formula-not-decoded --> Let's go through each term on the right hand side: - · p e f ( | ): This is the probability of the election outcome given the forecast, or the win probability of the candidate that actually won. - · p f ( ): This is our subjective judgement of how likely we think the forecast is to be correct before seeing the election",
 "outcome, also called the prior. - · p e ( ): This is the probability of the election outcome, which is created from two components: the probability of the election outcome given the forecast is correct, and the probability of the election outcome given the forecast is not correct. This requires subjective judgment in the second part: we will assume elections are a coin flip, and say that both candidates have a 50% chance to win in the case that the forecast is wrong. The equation for this using the law of total probability is p e ( ) = p e f ( | ) p f ( ) + p e ( |¬ f ) p ( ¬ f ). We assume that p e ( |¬ f ) = 0 5, . meaning in the case where the forecast is wrong each candidate has a 50% chance of winning. Now, let's look at the probability that two competing forecasts assigned to the presidential winner in 2012, 2016, and 2020. The large difference is the 2016 election, where Nate Silver gave Donald Trump a 29% chance to win, while Sam Wang gave Trump only a 1% chance. By successively applying Bayes' theorem to these three elections, and putting an initial prior of 50% on each forecast being right, we obtain the following probabilities of each forecast being correct So simply from observing the topline win probability across 3 elections, we assign roughly 9 times the probability that Nate Silver's forecast is correct relative to Sam Wang's and twice as likely as random guessing. This is clear evidence that Nate Silver's forecast is better than the alternatives, and to ignore this because it does not fit in a narrow null hypothesis significance testing framework (NHST) means throwing out good evidence that we should be incorporating. ## 4 A tweaked simulation Let's move now to NHST simulations. The main simulation in GKW's paper (Figure 1, p. 9; details in Appendix A.1, p. 23) claims that it would take 24 years to determine if a 95% accurate forecaster is better than random guessing. This is only true in the narrow case where we insist on using an accuracy metric and focus on 'hard' predictions (win/lose) rather than probabilities. GKW's focus on binary predictions and accuracy is puzzling in the context of a paper about the dangers of probabilistic forecasts. If we simply tweak the simulation so that forecasters produce probabilistic forecasts, we can plausibly distinguish 95% accurate (I only consider up to 90%) forecasters from chance in as little as 3 elections. I perform the following simulation: let's assume that a forecaster produces a noisy forecast that is on average right θ fraction of the time. The forecaster makes some assumptions, does some data analysis, and outputs a probability drawn from the following beta distribution: κ ∼ β cθ, c ( (1 -θ )). On average, κ = θ but there is noise around this mean. The shape parameter c controls",
 "how certain the forecaster is around this overall mean. Lower values of c will induce more spread while higher values of c will produce less spread around the mean of θ . I choose the values of c = 5 for a reasonable forecaster and c = 0 7 for an overconfident forecaster. . These choices are displayed in Figure 1 and are chosen heuristically (real forecasters likely choose more effectively). Figure 1: The two beta distribution concentrations we use, for a 0.7 correctness probability. <!-- image --> After drawing the correctness probability κ , we draw a random uniform draw υ ∼ Uniform(0 1) representing a TV pundit who just says stuff . Then, , 2 we compute the Brier score (the mean squared error but for probabilities) to judge correctness ( y -κ ) 2 and ( y -υ ) 2 . We average the Brier score over a number of elections N and examine whether we can use NHST and a simple t-test to determine if the forecaster is better than random guessing. We present data in one of two ways: the expected significance value over 1000 simulations for a given ( θ, N ), and the percentage of simulations that reach the traditional 95% significance level in a one-way t-test (forecaster better than pundit). Figure 2 (left panel) shows that a forecaster can be distinguished from random chance in as little as 3 elections. For forecasters in the empirical accuracy range (70% to 80%), the number is about 10 elections on average. Moving to Figure 3, we see that for a 75% accurate forecaster over 10 elections, about 70% of simulations we conducted were significant at the 95% level. For highly accurate forecasters (90%) only 3 elections are needed before virtually every simulation was significant. Figure 2: Left: a decently good forecaster that does not get overconfident can be distinguished from random guessing. Right: an overconfident forecaster is much harder to distinguish from random chance. <!-- image --> The lesson here is that random guessing produces terrible results, and even moderately accurate forecasters (in the 65% range) can be distinguished from random guessing in 20-40 election cycles. I note that these estimates are likely over-estimates of the amount of time needed to distinguish forecasts from random guessing, because real forecasts do not just draw numbers from a somewhat arbitrarily chosen beta distribution, but are highly tuned and refined over decades. As a final note, the right plot in both Figures 2 and 3 shows an on-averagecorrect but overconfident forecast. Such a forecast is much less likely to be Figure 3: Left: a decently good forecaster is distinguishable from random guessing. Right: an overconfident forecaster is much harder to distinguish. <!-- image --> distinighsed from random chance and therefore will likely be out-competed by better forecasts. ## 5 Combining elections Having established that there are scenarios where a relatively small number of elections can separate good forecasts from junk, I'm now going to argue that we can",
 "increase the number of 'elections' in two ways: first by combining presidential forecasts with other political forecasts, and second by examining plausibly uncorrelated microdata (such as demographic groups). GKW take the strong position that presidential elections are unicorns that cannot even be compared to other elections in the United States such as midterms. In Grimmer's words , they are 'distinctive.' 3 I don't believe this, and I don't believe the available evidence supports this. Rather, I think that if someone is good at forecasting a presidential, they are probably good at forecasting a midterm and vice versa. If we simply accept that midterms and presidentials both go in the analysis, we've doubled the number of elections to consider. So now we're hitting 10 cycles in 20 years rather than 40, and so on. Professional forecasters make detailed forecasts about primaries, off-year elections, midterms, and specials in addition to presidential elections. It is plausible that such less-prominent elections are more difficult to forecast than presidentials, meaning forecast skill at such elections may be actually more informative about presidential forecast skill than forecasting another presidential. If we focus on a number of 10 elections to reliably distinguish decent forecasts from noise using NHST, and insist that each election held on a single day only counts for a single election, we should be able to tell signal from noise in about 10 years, since there is at least one election cycle (and often times more) each year. ## 6 Microdata and effective elections The final part of my argument relies on increasing the number of 'effective elections' via microdata. While it is true that state-level results in presidential elections are highly correlated with one another, they are not perfectly correlated. And this increases the number of 'effective elections'. Using the Economist's state level correlation matrix from the 2020 cycle, we can compute the number of effective observations in the 50 states. First, we get the eigenvalues of the correlation matrix λ i , and then we compute the effective sample size <!-- formula-not-decoded --> This yields n eff = 5 12, meaning that each presidential election forecasted . at the state level contains the information of about 5 independent observations. So we can get to our heuristic 10 election threshold in two presidential elections by examining state-level forecasts. Such analysis can also be done at the house district level, or using even finer grained microdata, going all the way down to the voterfile level. It is beyond the scope of this paper to determine exactly how many 'effective elections' are contained in a full voterfile-level analysis of a single presidential election, but the microdata perspective is useful when thinking about how to evaluate forecasts. ## 7 We can evaluate forecasts As I have shown, we can evaluate forecasts in a few election cycles. This evaluation is not immediate, and there are obvious validation problems with a backtesting-only approach, but the situation is not as dire as GKW claim. Forecasters such as Nate Silver",
 'have produced forecasts over a period of almost two decades which can be easily shown to be informative compared to random guessing. While the harms of forecasts such as depressing turnout may be real (I take no position on this as its beyond the scope of this paper), the remedy for this potential problem is to insist that we present forecasts in responsible ways. Instead, GKW attempt to argue that forecasts themselves are uninformative, which is unlikely to be true if we simply consider all of the information available in each election and assume that forecasters of one type of election are likely to be good at other elections. I note that all of the major forecasts that have survived multiple election cycles are likely to be fairly good, as wrong forecasts are abandoned or changed in response to events. The collective body of political forecasting knowledge has continued to grow and I expect this indicates that our major forecasts are increasingly reliable.']

In [8]:
def cleaning_text(text):
     # quitar referencias tipo [1]
    text = re.sub(r"\[\d+\]", "", text)
    # limpiar caracteres
    text = re.sub(r"[^a-zA-Z0-9\s.,%\-]", " ", text)
    # normalizar espacios
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [9]:
train['clean_text'] = train['text'].apply(cleaning_text)
validation['clean_text'] = validation['text'].apply(cleaning_text)

In [12]:
def simple_split(text, chunk_size=60):
    txt_split = text.split()
    return [' '.join(txt_split[i:i+chunk_size]) for i in range(0, len(txt_split), chunk_size)]

In [10]:
sentence_transf_model = SentenceTransformer("BAAI/bge-base-en", device='cuda')
def embedding_function(texts):
    return sentence_transf_model.encode(texts, batch_size=64, show_progress_bar=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1010.09it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: BAAI/bge-base-en
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [13]:
all_chunks = []
chunk_pos = []

for i, text in enumerate(validation['clean_text']):
    chunks = simple_split(text)
    all_chunks.extend(chunks)
    chunk_pos.extend([i] * len(chunks))

In [14]:
embeddings = sentence_transf_model.encode(
    all_chunks,
    batch_size=64,
    show_progress_bar=True
)

Batches: 100%|██████████| 497/497 [01:41<00:00,  4.91it/s]

In [15]:
def semantic_chunking(chunks, doc_ids, embeddings, window_size=2, t = 0.9, max_len=300):
    #0.9
    merged_chunks = []

    chunks = list(chunks)
    doc_ids = list(doc_ids)
    
    current_chunk = chunks[0]
    current_indices = [0]
    current_doc_id = doc_ids[0]
    
    for i in range(1, len(chunks)):
        
        if doc_ids[i] != current_doc_id:
            merged_chunks.append({
                "text": current_chunk,
                "doc_id": current_doc_id,
                "chunk_indices": current_indices
            })
            
            current_chunk = chunks[i]
            current_indices = [i]
            current_doc_id = doc_ids[i]
            continue
        
        # ventana
        window_indices = current_indices[-window_size:]
        window_embeddings = embeddings[window_indices]
        
        current_embedding = embeddings[i].reshape(1, -1)
        
        sim = cosine_similarity(current_embedding, window_embeddings).max()        
        if sim >= t and len(current_chunk.split()) + len(chunks[i].split()) <= max_len:
            current_chunk += " " + chunks[i]
            current_indices.append(i)
        else:
            merged_chunks.append({
                "text": current_chunk,
                "doc_id": current_doc_id,
                "chunk_indices": current_indices
            })
            
            current_chunk = chunks[i]
            current_indices = [i]
            current_doc_id = doc_ids[i]
    
    # último chunk
    merged_chunks.append({
        "text": current_chunk,
        "doc_id": current_doc_id,
        "chunk_indices": current_indices
    })
    
    return merged_chunks

In [16]:
merged = semantic_chunking(all_chunks, chunk_pos, embeddings)

In [17]:
merged_df = pd.DataFrame(merged)

In [18]:
merged_df_clean = merged_df[merged_df['text'].str.len() > 100]

In [19]:
merged_df_clean.head()

                                                text  doc_id chunk_indices
0  Introduction Common sense understandings of pu...       0           [0]
1  literature by using Bacchi s 2009 What s the p...       0           [1]
2  the Council s written documents to further und...       0           [2]
3  review Foucauldian Discourse Analysis, which f...       0           [3]
4  of neoliberalism, Thatcherism welfare policy s...       0           [4]

In [26]:
validation = validation.reset_index(drop=True)

In [20]:
embeddings_chunks = sentence_transf_model.encode(
    merged_df_clean['text'].to_list(),
    batch_size=64,
    show_progress_bar=True
)

Batches: 100%|██████████| 398/398 [01:30<00:00,  4.41it/s]

In [27]:
summary_embedding = sentence_transf_model.encode(validation['summary'])[0]

merged_df_clean['scores'] = cosine_similarity(
    embeddings_chunks,
    [summary_embedding]
).flatten()

C:\Users\User\AppData\Local\Temp\ipykernel_24444\738744997.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df_clean['scores'] = cosine_similarity(

In [28]:
merged_df_clean.head()

,text,doc_id,chunk_indices,scores
0,Introduction Common sense understandings of pu...,0,[0],0.932996
1,literature by using Bacchi s 2009 What s the p...,0,[1],0.914908
2,the Council s written documents to further und...,0,[2],0.848610
3,"review Foucauldian Discourse Analysis, which f...",0,[3],0.883236
4,"of neoliberalism, Thatcherism welfare policy s...",0,[4],0.812073

In [29]:
merged_df_clean['scores'].mean()

0.7633121

In [30]:
merged_df_clean['scores'].std()

0.033186425

In [ ]:
def top_pct(group, pct=0.3):
    return floor(len(group)*pct)

In [31]:
df_sorted = (
    merged_df_clean
    .sort_values(['doc_id','scores'], ascending=[True, False])
    .groupby('doc_id', group_keys=False)
    .head(6)
    #.apply(lambda x: x.head(max(1, int(len(x)*0.2))))
)

In [32]:
df_sorted

,text,doc_id,chunk_indices,scores
0,Introduction Common sense understandings of pu...,0,[0],0.932996
42,". As Gamble 1989 argues, the apparent contradi...",0,"[44, 45]",0.916704
1,literature by using Bacchi s 2009 What s the p...,0,[1],0.914908
57,political actors respond. Discourse as a const...,0,[61],0.891107
3,"review Foucauldian Discourse Analysis, which f...",0,[3],0.883236
...,...,...,...,...
25503,2 the role longleaf pine forests and forestry ...,299,[31750],0.811435
25532,study provide a deeper understanding of the fa...,299,"[31795, 31796]",0.797809
25480,has become an important policy and management ...,299,[31725],0.797531
25505,that emerged within an interview was assigned ...,299,[31752],0.793770
25498,on forest management decisions. Although there...,299,[31745],0.785730

In [33]:
df_sorted['chunk_indices'] = df_sorted['chunk_indices'].apply(lambda x: min(x))

In [34]:
df_sorted.sort_values(['chunk_indices'], ascending=True, inplace=True)

In [35]:
df_sorted

,text,doc_id,chunk_indices,scores
0,Introduction Common sense understandings of pu...,0,0,0.932996
1,literature by using Bacchi s 2009 What s the p...,0,1,0.914908
3,"review Foucauldian Discourse Analysis, which f...",0,3,0.883236
40,"to reveal the what could have been, and engage...",0,42,0.876343
42,". As Gamble 1989 argues, the apparent contradi...",0,44,0.916704
...,...,...,...,...
25493,such as prescribed fire important to achieve r...,299,31738,0.819902
25498,on forest management decisions. Although there...,299,31745,0.785730
25503,2 the role longleaf pine forests and forestry ...,299,31750,0.811435
25505,that emerged within an interview was assigned ...,299,31752,0.793770
25532,study provide a deeper understanding of the fa...,299,31795,0.797809

In [36]:
df_final = df_sorted.groupby('doc_id')['text'].apply(" ".join)

In [ ]:
df_final =pd.DataFrame(df_final)

In [46]:
df_final

                                                     text
doc_id
0       Introduction Common sense understandings of pu...
1       in to participate in collaborative, inter- and...
2       Introduction Swear and taboo words in the subt...
3       context While the WVS has been conducted in mo...
4       Yet, the effects of time-averaging on archaeol...
...                                                   ...
295     on their support for CRBs. Within the survey, ...
296     that cover the majority of workers within thei...
297     Introduction Cultural studies has often attemp...
298     1. Introduction Twentieth century planners des...
299     has become an important policy and management ...

[300 rows x 1 columns]

In [47]:
df_final = df_final.join(train['summary'], how='left')

In [ ]:
df_final

,text,summary
doc_id,,
0,Introduction Common sense understandings of pu...,"In this article, Victor Fan argues that analys..."
1,"in to participate in collaborative, inter- and...",Problem definition: Physicians spend more than...
2,Introduction Swear and taboo words in the subt...,Literary translation is one of the most challe...
3,context While the WVS has been conducted in mo...,There is a long-running debate on evaluating f...
4,"Yet, the effects of time-averaging on archaeol...","Recently, ‘bimajyo’ (美魔女) came into focus in J..."
...,...,...
295,"on their support for CRBs. Within the survey, ...",Previous research has shown a consistent effec...
296,that cover the majority of workers within thei...,"In the hotel industry, the management of room ..."
297,Introduction Cultural studies has often attemp...,This study leverages sample data from the Amer...
298,1. Introduction Twentieth century planners des...,Global finance can be seen as a complex intern...
299,has become an important policy and management ...,The recent rise of sub-national minimum wage (...

In [49]:
df_final.to_pickle('validation_clean.pkl')

In [37]:
length = df_final.apply(len)

In [38]:
length.mean()

5241.73

In [42]:
length.std()

1975.7476728204738

In [31]:
np.percentile(merged_df_clean['scores'], [0, 25, 50, 75, 90, 100])

array([0.63136303, 0.7215758 , 0.74162096, 0.7636314 , 0.78436942,
       0.9272362 ])

In [34]:
top_k = int(len(merged_df_clean['scores']) * 0.3)
top_scores = sorted(merged_df_clean['scores'], reverse=True)[:top_k]

np.mean(top_scores)

0.7913983831250079

In [ ]:
k = int(len(chunks) * 0.3)

In [ ]:
validation['clean_chunks'] = validation['clean_chunks'].apply(cleaning_data)

In [ ]:
validation['clean_chunks'] = validation['clean_chunks'].apply(cleaning_data)

In [ ]:
def normalize(scores):
    scores = np.array(scores)
    return (scores - scores.min()) / (scores.max() - scores.min())

In [ ]:
def chunk_importance(chunks, summary):
    emb_chunks = sentence_transf_model.encode(chunks)
    emb_summary = sentence_transf_model.encode([summary])[0]

    similarities = cosine_similarity(emb_chunks, [emb_summary]).flatten()

    total = len(chunks)
    norm_sim = normalize(similarities) 
    scores_pos = [i/total for i in list(range(total))]
    norm_pos = normalize(scores_pos)
    
    return(norm_sim*0.8 + norm_pos*0.2)

In [ ]:
train['importance_score'] = validation['importance_score'].apply(chunk_importance)

In [22]:
sims = []

for i in range(1, len(embeddings_chunks)):
    sim = cosine_similarity(
        embeddings_chunks[i].reshape(1, -1),
        embeddings_chunks[i-1].reshape(1, -1)
    )[0][0]
    sims.append(sim)

print(min(sims), max(sims), sum(sims)/len(sims))

0.6417402 0.9787351 0.8680118135469157